"""V44 buy list for the small hardware: counts every screw, nut, washer and insert of both builds (F44_* from
build_v44_fasteners.py) plus the modelled extras (exit pulley axles, board standoffs, socket headers) -> hardware-summary.md.
Run after build_v44_fasteners.py. Counts are exact for the model; buy a pack (or +10 %) of each."""
from pathlib import Path
import json, re, collections

H = Path(__file__).resolve().parent
EXTRA = [   # (part-name prefix, item, per match)
    ('FM10_Exit_pulley_U625ZZ', 'uxcell U625ZZ nylon U-groove pulley bearing 5 x 20 x 7', 1),
    ('FM10_Exit_axle_ISO7379_5x25_M4_shoulder', 'Shoulder bolt ISO 7379, 5 mm shoulder x 25, M4 thread', 1),
    ('FM10_Exit_axle_M5_spacer_2mm', 'M5 spacer / shim washer 2 mm (5.2 ID)', 1),
    ('FM10_Exit_axle_M4_washer', 'M4 washer (ISO 7089)', 1),
    ('FM10_Exit_axle_M4_nut', 'M4 nyloc nut (ISO 10511)', 1),
    ('MOUNT_Pi_ceiling_standoffs_M2.5', 'M2.5 female-female brass hex standoff 3 mm', 'solids'),
    ('MOUNT_BMS_ceiling_standoffs_M3', 'M3 female-female brass hex standoff / spacer 2 mm', 'solids'),
    ('TRIAL_Teensy', '2.54 mm 14-pin female socket header, low profile (Teensy on the perfboard)', 2),
]

def order(item):
    m = re.match(r'M(\d+(?:\.\d+)?)(?:x(\d+))?', item)
    return (0 if 'insert' in item else 1 if 'x' in item.split()[0] else 2, float(m.group(1)) if m else 99, int(m.group(2) or 0) if m else 0, item)

def count(variant):
    r = json.loads((H / variant / 'revision.json').read_text())
    c = collections.Counter(h['size'] for h in r['hardware'] if str(h['part']).startswith('F44_'))
    for pre, item, k in EXTRA:
        for n in r['parts']:
            if n.startswith(pre):
                if k == 'solids':
                    import cadquery as cq
                    k_ = len(cq.Shape.importBrep(str(H / variant / (n + '.brep'))).Solids())
                else: k_ = k
                c[item] += k_
    return c

cs = {v: count(v) for v in ('printed', 'cnc')}
items = sorted(set(cs['printed']) | set(cs['cnc']), key=order)
L = ['# V44 hardware buy list', '',
     'Generated by `print-v44/hardware_summary.py` from the model (every F44_* screw / nut / washer / insert, plus the exit',
     'axles, ceiling standoffs and Teensy socket headers). Counts are exact for each build; buy packs (assortment kits cover most',
     'screws). Printed = the PA-CF / PETG prototype; CNC = the aluminium-plate build. Nothing is ordered.', '',
     '| Item | Printed | CNC |', '|---|---:|---:|']
for it in items: L.append(f"| {it} | {cs['printed'].get(it, 0) or '-'} | {cs['cnc'].get(it, 0) or '-'} |")
tot = {v: sum(c.values()) for v, c in cs.items()}
L += [f"| **Total pieces** | **{tot['printed']}** | **{tot['cnc']}** |", '',
      '## Shopping by kit (printed build)', '']
kit = collections.defaultdict(lambda: collections.Counter())
for it, n in cs['printed'].items():
    m = re.match(r'M(\d+(?:\.\d+)?)x(\d+) (countersunk|socket head)', it)
    if m: kit[f"M{m.group(1)} {m.group(3)} screws"][int(m.group(2))] += n
    elif 'insert' in it: kit['heat-set inserts (Ruthex RX, L4)'][it.split()[0]] += n
    elif 'nut' in it or 'washer' in it: kit['nuts / washers'][it] += n
for k in sorted(kit):
    L.append(f"- **{k}:** " + ', '.join(f"{n} x {s}{' mm' if isinstance(s, int) else ''}" for s, n in sorted(kit[k].items(), key=lambda q: str(q[0]).zfill(4))))
L += ['', 'Hole sizes the model is cut to (tune with `fit-coupons/`): inserts M2.5 3.6 / M3 4.0 / M4 5.6 mm, printed clearance',
      'M2.5 2.9 / M3 3.6 / M4 4.7 / M6 6.8 mm, self-tap pilots M2.5 2.2 / M3 2.6 mm.', '']
(H / 'hardware-summary.md').write_text('\n'.join(L), encoding='utf-8')
print('\n'.join(L))
